version: "3.9"

services:
  database:
    image: postgres:15.3
    container_name: database
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db
    ports:
      - "5432:5432"

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: grocery-senpai-main-backend
#    ports:
#      - "8080:8080"
#    restart: always
  qr:
    build:
      context: ./python
      dockerfile: Dockerfile
    container_name: grocery-senpai-qr
    ports:
      - "8083:8083"
    environment:
      PORT: 8083
    restart: always

#    depends_on:
#      - database
# lol