version: "3.9"

services:
  database:
    image: postgres:15.3
    container_name: database
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
