name: CD
on: [push]

jobs:
  backend_job:
    runs-on: ubuntu-latest
    name: building and ssh
    environment: backend
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: build and deploy
        env:
          KEYP: ${{ secrets.KEYP }}
          KEYYA: ${{ secrets.KEYYA }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          pwd;
          cd ..;
          ls -al;
          pwd;
          cd ./mainbackend;
          docker build -t "grocery_backend";
          docker save -o /tmp/grocery_backend.tar grocery_backend:latest;
          cd /tmp;
          ls -al;
          echo -n "${KEYP}" > id_ed25519.pub;
          echo -n "${KEYYA}" > id_ed25519;
          chmod 400 id_ed25519.pub;
          chmod 400 id_ed25519;
          echo "${KEYYA}" | ssh-add -;
          ssh-add -T id_ed25519.pub;
          ls -al;
          scp -oStrictHostKeyChecking=no /tmp/grocery_backend.tar ${SSH_USER}@${SSH_HOST}:/tmp;
          scp -oStrictHostKeyChecking=no update.sh ${SSH_USER}@${SSH_HOST}:/tmp;
          ssh ${SSH_USER}@${SSH_HOST} 'cd /tmp; ls -l; sh update.sh;';