name: CD
on: [push]

jobs:
  backend_job:
    runs-on: ubuntu-latest
    name: building and ssh
    environment: backend
    steps:
      - uses: actions/checkout@v3
      - name: directory tree
        run: tree

      - name: build

        run: |
          cd ./mainbackend;
          ls -al;
          docker ps;
          docker build -t grocery_backend:latest .;
          docker image ls;
          docker save -o /tmp/grocery_backend.tar grocery_backend:latest;
          ls -al;
          echo "ABOBA";
          ls /tmp -al;
      - name: deploy
        env:
          KEYP: ${{ secrets.KEYP }}
          KEYYA: ${{ secrets.KEYYA }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          pwd;
          echo -n "${KEYP}" > /tmp/id_ed25519.pub;
          echo -n "${KEYYA}" > /tmp/id_ed25519;
          chmod 400 /tmp/id_ed25519.pub;
          chmod 400 /tmp/id_ed25519;
          echo "${KEYYA}" | ssh-add -;
          ssh-add -T /tmp/id_ed25519.pub;
          ls -al;
          scp -oStrictHostKeyChecking=no /tmp/grocery_backend.tar ${SSH_USER}@${SSH_HOST}:/tmp;
          scp -oStrictHostKeyChecking=no update.sh ${SSH_USER}@${SSH_HOST}:/tmp;
          ssh ${SSH_USER}@${SSH_HOST} 'cd /tmp; ls -l; sh update.sh;';